export const CANCEL_GUIDES = {
  Netflix: {
    url: "https://www.netflix.com/cancelplan",
    steps: [
      "Откройте аккаунт Netflix на сайте (отмена с телефона в приложении недоступна).",
      "Перейдите в «Аккаунт» → «Тарифный план».",
      "Нажмите «Отменить подписку» и подтвердите. Доступ сохранится до конца оплаченного периода.",
    ],
  },
  Spotify: {
    url: "https://www.spotify.com/account/subscription/",
    steps: [
      "Войдите на spotify.com/account (не в мобильном приложении).",
      "Откройте раздел «Подписка».",
      "Выберите «Изменить или отменить» → «Отменить Premium».",
    ],
  },
  iCloud: {
    url: "https://apps.apple.com/account/subscriptions",
    steps: [
      "На iPhone: Настройки → ваше имя → Подписки.",
      "Выберите iCloud+ и нажмите «Отменить подписку».",
      "На Mac: Системные настройки → Apple ID → Медиаматериалы и покупки → Управлять.",
    ],
  },
  "YouTube Premium": {
    url: "https://www.youtube.com/paid_memberships",
    steps: [
      "Откройте YouTube → аватар → «Платные подписки».",
      "Выберите YouTube Premium → «Управление подпиской».",
      "Нажмите «Отменить членство».",
    ],
  },
  "ChatGPT Plus": {
    url: "https://chatgpt.com/#settings",
    steps: [
      "Откройте ChatGPT → Settings → My plan.",
      "Нажмите Manage my subscription — откроется страница Stripe/OpenAI.",
      "Выберите Cancel plan. Доступ Plus действует до конца биллинга.",
    ],
  },
  "Adobe Creative Cloud": {
    url: "https://account.adobe.com/plans",
    steps: [
      "Войдите в account.adobe.com/plans.",
      "Выберите план → «Управление планом» → «Отменить план».",
      "Если есть обязательный срок — Adobe покажет дату и возможные удержания.",
    ],
  },
  "Яндекс Плюс": {
    url: "https://plus.yandex.ru/",
    steps: [
      "Откройте plus.yandex.ru и войдите в аккаунт.",
      "Перейдите в управление подпиской.",
      "Отключите автопродление. Если Плюс куплен через Apple/Google — отменяйте в их магазине.",
    ],
  },
  Figma: {
    url: "https://www.figma.com/settings",
    steps: [
      "Откройте Figma → Settings → Billing.",
      "Выберите команду или личный план → Cancel plan.",
      "Черновики сохранятся, облачные возможности урежутся после окончания периода.",
    ],
  },
};

export const SEED = [
  {
    id: "seed-netflix",
    name: "Netflix",
    price: 899,
    currency: "RUB",
    nextBilling: "2026-08-24",
    category: "entertainment",
    period: "month",
    icon: "netflix",
    status: "active",
  },
  {
    id: "seed-spotify",
    name: "Spotify",
    price: 169,
    currency: "RUB",
    nextBilling: "2026-08-25",
    category: "entertainment",
    period: "month",
    icon: "spotify",
    status: "active",
  },
  {
    id: "seed-icloud",
    name: "iCloud",
    price: 149,
    currency: "RUB",
    nextBilling: "2026-08-26",
    category: "software",
    period: "month",
    icon: "icloud",
    status: "active",
  },
  {
    id: "seed-yt",
    name: "YouTube Premium",
    price: 399,
    currency: "RUB",
    nextBilling: "2026-09-04",
    category: "entertainment",
    period: "month",
    icon: "youtube",
    status: "active",
  },
  {
    id: "seed-gpt",
    name: "ChatGPT Plus",
    price: 20,
    currency: "USD",
    nextBilling: "2026-09-08",
    category: "work",
    period: "month",
    icon: "ai",
    status: "active",
  },
  {
    id: "seed-adobe",
    name: "Adobe Creative Cloud",
    price: 599.88,
    currency: "USD",
    nextBilling: "2026-12-01",
    category: "software",
    period: "year",
    icon: "adobe",
    status: "active",
  },
  {
    id: "seed-plus",
    name: "Яндекс Плюс",
    price: 399,
    currency: "RUB",
    nextBilling: "2026-08-29",
    category: "entertainment",
    period: "month",
    icon: "plus",
    status: "active",
  },
  {
    id: "seed-figma",
    name: "Figma",
    price: 15,
    currency: "USD",
    nextBilling: "2026-09-15",
    category: "work",
    period: "month",
    icon: "figma",
    status: "active",
  },
  {
    id: "seed-power",
    name: "Электроэнергия",
    price: 3200,
    currency: "RUB",
    nextBilling: "2026-09-01",
    category: "utilities",
    period: "month",
    icon: "power",
    status: "active",
  },
  {
    id: "seed-gym",
    name: "World Class",
    price: 8900,
    currency: "RUB",
    nextBilling: "2026-09-10",
    category: "utilities",
    period: "month",
    icon: "gym",
    status: "archived",
    archivedAt: "2026-06-10",
  },
];
